In [36]:
import numpy as np

np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

np.zeros((3, 3))

np.ones((3, 3))

x=np.eye(3)
x.shape
np.empty(5)

np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [26]:
2/3

0.6666666666666666

In [27]:
2/2

1.0

In [37]:
np = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [40]:
np

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [42]:
np[:3,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])